### PR TITLE
OSFUSE-529: Added fabric8 arquillian quickstart

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@jimmidyson any idea about what's wrong, it looks like mvn is not installed on the node

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
I have no idea... Settings look fine to me, just looks like Maven has disappeared.

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
For now I've specified a Maven version that will be automatically installed when this job runs if it's not available. You can do the same in each other job as required for now until we get this sorted.

**Comment by dhirajsb** [comment]
[merge] lgtm

**Comment by dhirajsb** [comment]
[merge] lgtm

**Pull request merged**
